#!/bin/bash

adduser --system --disabled-password \
  --home /usr/local/var/lib/couchdb --no-create-home \
  --shell=/bin/bash --group --gecos "" couchdb

# copy geocouch configuration to make couchdb aware of the new handlers
cp /opt/geocouch-couchdb1.3.x/etc/couchdb/default.d/geocouch.ini /usr/local/etc/couchdb/default.d/geocouch.ini

chown -R couchdb:couchdb /usr/local/var/lib/couchdb \
  /usr/local/var/log/couchdb \
  /usr/local/var/run/couchdb \
  /usr/local/etc/couchdb \
  /opt/geocouch-couchdb1.3.x/ebin

chmod 0770 /usr/local/var/lib/couchdb \
  /usr/local/var/log/couchdb \
  /usr/local/var/run/couchdb \
  /usr/local/etc/couchdb \
  /opt/geocouch-couchdb1.3.x/ebin

chmod 664 /usr/local/etc/couchdb/*.ini
chmod 775 /usr/local/etc/couchdb/*.d

rm /etc/logrotate.d/couchdb /etc/init.d/couchdb 2&>1

ln -s /usr/local/etc/logrotate.d/couchdb /etc/logrotate.d/couchdb
ln -s /usr/local/etc/init.d/couchdb /etc/init.d/couchdb

update-rc.d couchdb defaults